version: "3.7"
services:
  server:
    image: knappster/arma-reforger-server:latest
    restart: unless-stopped
    ports:
      - "2001:2001/udp"
      - "17777:17777/udp"
      - "1376:1376/tcp"
    volumes:
      - data:/home/steam
      - ./server-config.json:/home/steam/server-config.json

volumes:
  data:
    driver: local
